### PR TITLE
Cherry-pick #7 (Project infra RGB)

### PR DESCRIPTION
**Pull request by 130s**
Since #7 is merged in already, this should be mergeable once CI passes.

### CODE REVIEW

**Comment by geoffreychiou** [comment]
@130s can you revert this?

1. It doesn't build without errors (warnings as errors, complains about unused variables).
1. When I launch cameras, images are not published.

I reverted to commit before this and everything started working again.

Edit: Looks like the build failing is not consistent across different machines, however I am still unable to get images on the topic.

**Comment by geoffreychiou** [comment]
@shaun-edwards says to not revert, logging an issue.

**Comment by shaun-edwards** [comment]
@130s, this one is really on me since I asked you to merge this.  I logged an issue to address here: https://github.com/plusone-robotics/realsense/issues/13

In the short term, I'd like to suggest we create a branch for IR-RGB support and then revert this change as @geoffreychiou suggests on the mainline.  We should then make sure all internal products link to the proper branches.

After #13 is addressed, we can unify the branches again.

Thoughts? @130s, @geoffreychiou

**Comment by 130s** [comment]
I see, reverting this PR in https://github.com/plusone-robotics/realsense/pull/14

**Pull request merged**
