### PR TITLE
added changes to optionally enable infrared rgb frame

### PR DESCRIPTION
**Pull request by 130s**
See https://github.com/plusone-robotics/realsense/pull/30#issuecomment-719694336 for the description of this PR.

### CODE REVIEW

**Comment by abhijitmajumdar** [comment]
@130s I have tested this with a real system with both the L515 and the D415. I feel this is ready for review

**Comment by abhijitmajumdar** [comment]
### What this PR does
- Adds a new ROS param `infrargb` flag to the realsense node, which enables the a realsense camera to configure the infrared camera (which is usually used for depth estimation) to also be used as the RGB camera.
  - Limitations:
    - This is only possible with realsense cameras which use infrared cameras that support RGB stream (for example the `realsense D415` does, but the `realsense D435` and `realsense L515` do not)
  - Advantages:
    - This is helpful because the frame of reference for the depth frame and the RGB frame is the same eliminating frame conversion errors
  - Disadvantages:
    - The depth exposure is the same as the RGB exposure so fixing color image and fixing point cloud through exposure may have contradictory results and requires a happy medium
    - The RGB image now will have the infrared pattern in it since the infrared cameras do not have a filter for IR for the obvious reason
- Removed the `librealsense2` dependency in package definition to avoid automatic download of the ros distributed version of the library causing a conflict with the already installed driver (preferably done to restrict driver version and control the installation process)

**Comment by 130s** [comment]
> Removed the librealsense2 dependency in package definition to avoid automatic download of the ros distributed version of the library causing a conflict with the already installed driver (preferably done to restrict driver version and control the installation process)

When making a PR to the intel repo, the dependency needs to be reverted back in. 

@abhijitmajumdar Do you mind splitting a commit into 2 per change? I thought I would do that but the branch is on your fork.

**Comment by abhijitmajumdar** [comment]
> Do you mind splitting a commit into 2 per change? I thought I would do that but the branch is on your fork.

@130s Done

**Comment by 130s** [comment]
So simpler than the original (?) PR made months ago https://github.com/plusone-robotics/realsense/pull/21. Strategy changed? 

Nothing clicks my mind. Merging.

**Comment by abhijitmajumdar** [comment]
> Strategy changed?

Upstream changes since then have enabled this change to become simpler since then

**Pull request merged**
