### PR TITLE
Revert change to initialization timing.

### PR DESCRIPTION
**Pull request by malban**

### CODE REVIEW

**Comment by 130s** [comment]
Hm. Only Bionic job failed.

**Comment by 130s** [comment]
@malban Just wondering if #29, which is unmerged yet, has anything to do with the test failure.

**Comment by malban** [comment]
> @malban Just wondering if #29, which is unmerged yet, has anything to do with the test failure.

Possibly.  I'll take a look

**Comment by malban** [comment]
@130s I don't think so.  #29 looks like it moves farther away from the upstream code, not closer, so I don't think it will help with the tests.

**Comment by malban** [comment]
@130s The last discrepancy that I could see making a difference is: https://github.com/IntelRealSense/realsense-ros/pull/1504/files#diff-a54ad2538ccd7b6cce4c6c6d8f57af062bded3d802b88e7b938faefb6f02f4caR1725

I'll revert that and see if it resolves the issue.

**Comment by 130s** [comment]
Thanks @malban! Offline we discussed about squashing commits. I haven't seen a squashed commit(s) in this PR so I assume you were suggesting to squash when merging this PR, which I'll do now.

**Pull request merged**
