### PR TITLE
WIP: Node should stay alive even if realsense disconnects

### PR DESCRIPTION
**Pull request by jonlwowski012**
Node should stay alive even if realsense disconnects. The node will continually look for a new realsense if the current realsense disconnects.

The pull request depends on https://github.com/plusone-robotics/realsense/pull/16/

# Review items
- [x] Blocked by https://github.com/plusone-robotics/realsense/pull/19 -> Not needed https://github.com/plusone-robotics/realsense/pull/17#issuecomment-464346965
- [x] Verify w/hardware 
- [ ] Rebase to the origin to remove #16 from the change in this PR.
- [ ] CI passes.
  - Due to flaky tests (kindf of reported at the upstream https://github.com/intel-ros/realsense/issues/619#issuecomment-464238122 although that's not the right approach to fix an issue), test section likely fails but Travis CI will unlikely report it as a failure.

### CODE REVIEW

**Comment by jonlwowski012** [comment]
@130s This is the fix for the reconnection issue.

**Comment by jonlwowski012** [comment]
@130s When can we get this merged?

**Comment by 130s** [comment]
I've updated OP to add review items.

> # Review items
> :
> - [ ] Rebase to the origin's head to remove #16 from the change in this PR.

Can you @jonlwowski012 rebase?

For some reason the change view https://github.com/plusone-robotics/realsense/pull/17/files doesn't seem to be aware that #16 was already merged, so that it still shows the changes included in #16, which populates the changes that are not necessarily suggested in this PR. Since the changes in this PR are cherry-picks from the upstream, I don't attempt to do code-review, but still want to sanity-check at minimum. So I want the change view to be in clean state.

> - [ ] Blocked by https://github.com/plusone-robotics/realsense/pull/19

This criteria is actually unnecessary because:
- CI is "broken" https://github.com/intel-ros/realsense/issues/619#issuecomment-464238122 and even https://github.com/plusone-robotics/realsense/pull/19 doesn't attempt to fix it.
- For this PR, CI already passed (with the same glitch as https://github.com/intel-ros/realsense/issues/619#issuecomment-464238122).

**Comment by jonlwowski012** [comment]
This has been reopened in https://github.com/plusone-robotics/realsense/pull/20

**Pull request closed without merging**
