### PR TITLE
Added code to fix hardware reset issues

### PR DESCRIPTION
**Pull request by jonlwowski012**
This code is to provide the updates to fix the bug where restarting a launch file with the realsense sensor often causes the cameras to fail.

I have not experienced the problem after this fix, but will test further to verify.

This fix came from the PR in the original intel repo here: https://github.com/intel-ros/realsense/pull/455/files

### CODE REVIEW

**Comment by jonlwowski012** [comment]
@shaun-edwards Can you please review

**Comment by 130s** [comment]
> This fix came from the PR in the original intel repo here: https://github.com/intel-ros/realsense/pull/455/files

Any reason you squashed 4 commits into a single commit and changed authorship?

In general when cherry-picking changes from another repository, you should maintain the original commits and the authorship (Then if you have to add your own change just add more commits). There's no rule in opensource community to restrict that AFAIK, but it's just bona fides among developers I think.

**Comment by jonlwowski012** [comment]
@130s Should I redo this MR then and cherry pick the changes?

**Comment by 130s** [comment]
> Should I redo this MR then and cherry pick the changes?

You can just update this PR by removing the current commit with `git reset` and cherry-picking by `git cherry-pick`. Updating the same PR is generally preferred, and those commands are worth getting familiar. But I leave that up to you this time.

**Comment by jonlwowski012** [comment]
@130s @shaun-edwards I cherry picked the commit and now there is a lot more that got pulled in than just the necessary changes. Let me know if this a problem.

**Comment by jonlwowski012** [comment]
But I did check and the fix still works.

**Comment by jonlwowski012** [comment]
@130s Do you know why CI is failing? It says that `error: ‘class rs2::processing_block’ has no member named ‘process’` but it does exist when building on my machine.

**Comment by 130s** [comment]
I see in https://github.com/intel-ros/realsense/pull/455 there are 6 commits, but the last one is a merge commit, which pulls in all associated commits in a kind of implicitly manner. If all of those commits are required to address the issue in question, then we need all. Can you @jonlwowski012 confirm?

Once that's confirmed I can help CI. As of now CI failed for what looks like C++ coding error, which makes me feel there may or may not be unnecessary commit merged in (but it's hard to tell as `intel-ros/realsense` no longer runs CI so buildability might not be guaranteed):
https://travis-ci.org/plusone-robotics/realsense/builds/487264607#L3117
```
/home/travis/catkin_ws/src/realsense/realsense2_camera/src/base_realsense_node.cpp:732:56: error: ‘class rs2::processing_block’ has no member named ‘process’
                         frameset = filter_it->_filter->process(frameset);
                                                        ^
realsense/realsense2_camera/CMakeFiles/realsense2_camera.dir/build.make:75: recipe for target 'realsense/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/base_realsense_node.cpp.o' failed
make[2]: *** [realsense/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/base_realsense_node.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1193: recipe for target 'realsense/realsense2_camera/CMakeFiles/realsense2_camera.dir/all' failed
make[1]: *** [realsense/realsense2_camera/CMakeFiles/realsense2_camera.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j2 -l2" failed
The command "catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release" failed and exited with 1 during .
```

**Comment by jonlwowski012** [comment]
Opened a new PR.
https://github.com/plusone-robotics/realsense/pull/16/

**Pull request closed without merging**
